Update mirroring.yml

diff --git a/.github/workflows/mirroring.yml b/.github/workflows/mirroring.yml
--- a/.github/workflows/mirroring.yml
+++ b/.github/workflows/mirroring.yml
@@ -1,4 +1,4 @@
-name: Mirror to GitFlic
+name: Mirror to Git Repositories
 
 on:
   push:
@@ -14,27 +14,23 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Add gitflic remote
+      - name: Add remotes
         run: |
           git remote add gitflic https://aerodisk_open_vair:${{ secrets.GITFLIC_TOKEN }}@gitflic.ru/project/aerodisk_open_vair/openvair.git
-
-      - name: Add GitLab remote
-        run: |
           git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@git.aerodisk.ru/openvair/openvair.git
-
-      - name: Add GitVerse remote
-        run: |
           git remote add gitverse https://Aerodisk:${{ secrets.GITVERSE_TOKEN }}@gitverse.ru/Aerodisk/openvair.git
 
+      - name: Fetch full history
+        run: git fetch --all
 
       - name: Force push to GitFlic
         run: |
-          git push --force gitflic
+          git push --force gitflic || echo "Push to GitFlic failed."
 
       - name: Force push to GitLab
         run: |
-          git push --force gitlab
+          git push --force gitlab || echo "Push to GitLab failed."
 
       - name: Force push to GitVerse
         run: |
-          git push --force gitverse
+          git push --force gitverse || echo "Push to GitVerse failed."
